name: latest_release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: latest_release
      run: |
          python ./tests/pip_install_latest.py ywatanabe1989/mngs
          python ./tests/test_mngs_template.py
