name: pypi_latest

on:
  push:
    branches:
      - main      
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: pypi_latest
      run: |
          pip install mngs
          python ./tests/test_mngs_template.py
