name: import

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      
    - name: Install mngs
      run |
          pip install git+https://git@github.com/ywatanabe1989/mngs.git@develop
          python ./tests/test_import.py
