name: import

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: import
      run: |
          pip install git+https://github.com/ywatanabe1989/mngs.git@develop  # [REVISED]
          python ./tests/test_import.py
