# Time-stamp: "2024-11-08 02:12:08 (ywatanabe)"
# File: ./mngs/.github/workflows/install-latest-release.yml

name: install-latest-release

on:
  push:
    branches:
      - main
      # - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: latest_release
      run: |
          python -m pip install -U pip
          python ./tests/custom/test_pip_install_latest.py ywatanabe1989/mngs
          python ./tests/custom/test_mngs_run.py
