# Timestamp: "2025-02-27 13:00:40 (ywatanabe)"
# File: /home/ywatanabe/proj/mngs_repo/.github/workflows/install-develop-branch.yml

# Time-stamp: "2025-02-27 13:00:40 (ywatanabe)"
# File: ./mngs/.github/workflows/install-develop-branch.yml

name: install-develop-branch

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install-develop-branch
      run: |
          python -m pip install -U pip
          pip install git+https://github.com/ywatanabe1989/mngs.git@develop
          python ./tests/custom/test_mngs_run.py

# EOF