# Time-stamp: "ywatanabe (2024-11-08 00:28:26)"
# File: ./mngs_repo/.github/workflows/install-develop-branch.yml

name: install-develop-branch

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: develop
      run: |
          python -m pip install -U pip
          pip install git+https://github.com/ywatanabe1989/mngs.git@develop
          python ./tests/test_mngs_run.py
