# Time-stamp: "ywatanabe (2024-11-08 01:01:10)"
# File: ./mngs/.github/workflows/install-latest-release.yml

name: install-latest-release

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: latest_release
      run: |
          python -m pip install -U pip
          python ./tests/pip_install_latest.py ywatanabe1989/mngs
          python ./tests/custom/test_mngs_run.py
