# Timestamp: "2025-02-27 11:24:35 (ywatanabe)"
# File: /home/ywatanabe/proj/mngs_repo/.github/workflows/install-pypi-latest.yml

# Time-stamp: "2025-02-27 11:24:35 (ywatanabe)"
# File: ./mngs/.github/workflows/install-pypi-latest.yml

name: install-pypi-latest

on:
  push:
    branches:
      - main      
      # - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install-pypi-latest
      run: |
          pip install -U pip        
          pip install mngs
          python ./tests/custom/test_mngs_run.py

# EOF