# Timestamp: "2025-02-27 11:24:43 (ywatanabe)"
# File: /home/ywatanabe/proj/mngs_repo/.github/workflows/install-latest-release.yml

name: install-latest-release

on:
  push:
    branches:
      - main
      # - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: latest_release
      run: |
          python -m pip install -U pip
          python ./tests/custom/test_pip_install_latest.py ywatanabe1989/mngs
          python ./tests/custom/test_mngs_run.py

# EOF