# Time-stamp: "2024-11-07 19:28:00 (ywatanabe)"
# File: ./mngs_repo/.github/workflows/install-latest-release.yml

name: install-latest-release

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: latest_release
      run: |
          python ./tests/pip_install_latest.py ywatanabe1989/mngs
          python ./tests/test_mngs_run.py
