# Time-stamp: "2024-11-08 01:42:51 (ywatanabe)"
# File: ./mngs/.github/workflows/install-pypi-latest.yml

name: install-pypi-latest

on:
  push:
    branches:
      - main      
      # - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install-pypi-latest
      run: |
          pip install -U pip        
          pip install mngs
          python ./tests/custom/test_mngs_run.py
