name: pip-install

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install mngs
      run: pip install git+ssh://git@github.com/ywatanabe1989/mngs.git@develop
